name: Typescript Check
on: push
jobs:
  typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Check Typescript
        run: npm run build:typescript
