name: E2E on Chrome

on: [push]

jobs:
  end-to-end:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports: ['5432:5432']
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      CLERK_JWT_KEY: ${{ secrets.CLERK_JWT_KEY }}
      CLERK_API_KEY: ${{ secrets.CLERK_API_KEY }}
      NEXT_PUBLIC_CLERK_FRONTEND_API: ${{ secrets.NEXT_PUBLIC_CLERK_FRONTEND_API }}
    steps:
      - name: Checkout 🏁
        uses: actions/checkout@v3
      - name: Set-up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.14.0
      - name: Install dependencies and Build
        run: |
          npm ci
          npm run build
      - name: Write Database URL
        run: |
          echo '${{ secrets.DATABASE_URL }}' > .env.development
      - name: Generate Prisma Database
        run: |
          npx prisma migrate deploy
      - name: Create a CI cypress.env.json file ✍️
        run: |
          echo '${{ secrets.CYPRESS_ENV_CI }}' > cypress.env.json
      - name: Cypress run ⛰️
        uses: cypress-io/github-action@v5
        with:
          project: ./
          browser: chrome
          build: npm run build
          start: npm run start
          wait-on: 'http://localhost:3000'
      - name: Upload Video Arifacts Available on Summary Page
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: videos
          path: cypress/videos/
          retention-days: 5
