name: E2E on Chrome

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          project: ./
          browser: chrome
          build: npm run build
          start: npm run start
          wait-on: ${{ vars.BASE_URL }}
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          CLERK_JWT_KEY: ${{ secrets.CLERK_JWT_KEY }}
          CLERK_API_KEY: ${{ secrets.CLERK_API_KEY }}
          NEXT_PUBLIC_CLERK_FRONTEND_API: ${{ secrets.NEXT_PUBLIC_CLERK_FRONTEND_API }}
