name: Lint and Prettier
on: push
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: Check prettier
        run: npx prettier --check .
      - name: Run prettier
        run: npx prettier --write .
      - name: Lint with ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx --fix
